# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :CD do |values|

    gym(scheme: 'ViewAttributes', project: "ViewAttributes.xcodeproj", clean: true, silent: true, include_bitcode: false, export_method: 'ad-hoc')

    emails = values[roshanbaig17@gmail.com] ? values[:test_email] : ['[email]'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: '[b8f26af27cf81a1ccbd77396878ed642104e095b]',
             build_secret: '[a96f1a78a366049fa916f6fe77578a730dfd27e6981d34030ef64e40254ad234]',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    end
end
end
